from langchain.messages import SystemMessage, HumanMessage
from shared_resources import llm, memory 

def conversational_agent(query: str):
    """
    A general-purpose conversational handler for casual dialogue, greetings, and non-technical queries.

    This tool should be invoked when the user's input does not require specific technical tools, 
    external data retrieval, or document searching. it is designed to:
    1. Handle greetings and small talk (e.g., "Hello", "How are you?").
    2. Provide empathetic and engaging responses to open-ended conversational prompts.
    3. Assist with creative brainstorming and general assistance.
    4. Maintain a friendly, human-like persona while managing context through conversation history.

    Args:
        query (str): The user's natural language input or conversational message.

    Returns:
        str: A friendly and contextually appropriate text response generated by the LLM.

    """
        
    system_msg = SystemMessage(content="""
    You are a versatile conversational agent designed for natural, friendly, and human-like interactions.
    You handle non-technical queries, casual dialogue, brainstorming, and general assistance.
    """)

    # Getting the history from memory
    history = memory.load_memory_variables({})["history"]

    # Constructing messages
    messages = [system_msg] + history + [HumanMessage(content=query)]
    
    # Invoking model
    response = llm.invoke(messages)

    # Saving to memory
    memory.save_context({"input": query}, {"output": response.content})

    print("This is the Response generated by the general agent")
    return response.content
