import asyncio
from fastmcp import Client
from langchain_classic.agents import AgentExecutor, create_tool_calling_agent
from langchain.tools import tool
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from src.shared_resources import llm, memory

# MCP Client Connection
client = Client("http://127.0.0.1:8000/sse")

async def call_mcp_tool(tool_name, **kwargs):
    """
    Function to call mcp tools
    """
    async with client:
        response = await client.call_tool(tool_name, kwargs)
        if hasattr(response, 'content') and len(response.content) > 0:
            return response.content[0].text
        return str(response)


def extract_string(value) -> str:
    """Handles cases where the LLM passes a dict instead of a plain string."""
    if isinstance(value, dict):
        return value.get("value") or value.get("query") or value.get("topic") or value.get("greetings") or str(value)
    return str(value)

# Creating tools for the llm to interact with
@tool
async def call_general_agent(query:str)->str:
    """
        A general-purpose conversational handler for casual dialogue, greetings, and non-technical queries.

        This tool should be invoked when the user's input does not require specific technical tools, 
        external data retrieval, or document searching. it is designed to:
        1. Handle greetings and small talk (e.g., "Hello", "How are you?").
        2. Provide empathetic and engaging responses to open-ended conversational prompts.
        3. Assist with creative brainstorming and general assistance.
        4. Maintain a friendly, human-like persona while managing context through conversation history.

        Args:
            query (str): The user's natural language input or conversational message.

        Returns:
            str: A friendly and contextually appropriate text response generated by the LLM.

    """
    return await call_mcp_tool("conversational_agent", query=query)

@tool
async def call_technical_agent(query:str)->str:
    """
    A multi-tool orchestrator that selects and executes the most appropriate research or search tool 
    based on the user's query.

    This function acts as a meta-agent that coordinates between five specialized data sources:
    1. Local RAG (vector_search): Internal document retrieval.
    2. ArXiv (search_papers): Technical and academic research papers.
    3. GitHub (search_repo_by_topic): Trending software repositories and codebases.
    4. NewsData (fetch_latest_news): Real-time technology and industry news.
    5. Web Search (websearch): General internet queries for broad information.

    Args:
        query (str): The specific question, topic, or research interest provided by the user.

    Returns:
        str: Returns the string output.
    """
    return await call_mcp_tool("agent_fetch_tools", query=query)

tools = [call_general_agent, call_technical_agent]

# Instructions for the Orchestrator
prompt = ChatPromptTemplate.from_messages([
    ("system",
    "You are a HIGH-LEVEL ORCHESTRATOR AGENT responsible for managing and routing user queries.\n\n"

    "You do NOT answer queries directly unless they are simple conversational queries.\n"
    "Your primary role is to decide which specialized agent should handle the request.\n\n"

    "You have access to the following tools (agents):\n"
    "- general_agent → Handles casual conversation, general queries, and non-technical discussions\n"
    "- technical_agent → Handles web search, coding, research, AI/ML, blockchain, APIs, debugging, and technical topics\n\n"

    "CORE RESPONSIBILITIES:\n"
    "1. Analyze the user query and classify it as GENERAL or TECHNICAL.\n"
    "2. Call the appropriate agent tool.\n"
    "3. Pass relevant chat history as context.\n"
    "4. Return the agent's response to the user.\n\n"

    "ROUTING GUIDELINES:\n"
    "- Use technical_agent for anything involving code, errors, system design, ML, AI, blockchain, APIs, or research.\n"
    "- Use general_agent for casual conversation, greetings, or non-technical queries.\n"
    "- If the query is ambiguous, prefer technical_agent.\n\n"

    "MEMORY USAGE:\n"
    "- Use chat history to maintain context.\n"
    "- Do NOT store or manage memory for sub-agents; only pass relevant history.\n\n"

    "CONSTRAINTS:\n"
    "- Do NOT attempt to use external tools like search, RAG, or GitHub directly.\n"
    "- Do NOT generate detailed technical answers yourself.\n"
    "- Do NOT mention internal architecture, agents, or routing decisions.\n"
    "- Always respond with the final answer from the selected agent.\n\n"

    "EFFICIENCY RULE:\n"
    "- Call ONLY ONE agent per query.\n"
    ),

    MessagesPlaceholder(variable_name="history"),

    ("human", "{input}"),

    MessagesPlaceholder(variable_name="agent_scratchpad"),
    ])

# Defining the Orchestrator
agent = create_tool_calling_agent(
    llm=llm,
    tools=tools,
    prompt=prompt
    )

# Creating the Executor
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose= False, memory=memory)

async def main():
    while True:
        query = input("User: ")
        
        if query.lower() in ("exit", "quit", "bye"):
            print("Goodbye!")
            break

        response = await agent_executor.ainvoke({"input": query})
        print(f"\nAgent:{response['output']}\n")

    await client.close()

if __name__ == "__main__":
    asyncio.run(main()) 